### ISSUE TITLE
pi_air_quality_monitor_web_1 exited with code 1

### ISSUE THREAD

**Issue by easyas314** [rydercalmdown/pi_air_quality_monitor#1]
Apologies in advance; not sure what I'm doing here ...
As title implies, this project is failing and I don't see an obvious cause.
I'm running a rpi4B+ w/latest raspOS; only USB connection in the sensor USB adaptor. The red light it steady on and there's a green light that blinks at a regular interval.

Here's the whole output from the terminal
```
$ make run
make[1]: Entering directory '/home/pi/pi_air_quality_monitor'
Starting pi_air_quality_monitor_redis_1 ... done
Starting pi_air_quality_monitor_web_1   ... done
Attaching to pi_air_quality_monitor_redis_1, pi_air_quality_monitor_web_1
redis_1  | 1:C 08 Jul 2021 01:08:01.370 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 08 Jul 2021 01:08:01.370 # Redis version=6.2.4, bits=32, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 08 Jul 2021 01:08:01.370 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 08 Jul 2021 01:08:01.372 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 08 Jul 2021 01:08:01.373 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
redis_1  | 1:M 08 Jul 2021 01:08:01.374 * Running mode=standalone, port=6379.
redis_1  | 1:M 08 Jul 2021 01:08:01.374 # Server initialized
redis_1  | 1:M 08 Jul 2021 01:08:01.374 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 08 Jul 2021 01:08:01.375 * Loading RDB produced by version 6.2.4
redis_1  | 1:M 08 Jul 2021 01:08:01.375 * RDB age 43 seconds
redis_1  | 1:M 08 Jul 2021 01:08:01.375 * RDB memory usage when created 0.63 Mb
redis_1  | 1:M 08 Jul 2021 01:08:01.375 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 08 Jul 2021 01:08:01.375 * Ready to accept connections
web_1    | Traceback (most recent call last):
web_1    |   File "app.py", line 15, in <module>
web_1    |     aqm = AirQualityMonitor()
web_1    |   File "/code/AirQualityMonitor.py", line 13, in __init__
web_1    |     self.sds = SDS011(port='/dev/ttyUSB0')
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 132, in __init__
web_1    |     self.probe()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 139, in probe
web_1    |     firmware_version_data = self.get_firmware_version()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 226, in get_firmware_version
web_1    |     return self.request(cmd)
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 234, in request
web_1    |     resp = self.rx_cmd_resp_queue.get(timeout=10)
web_1    |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
web_1    |     raise Empty
web_1    | _queue.Empty
pi_air_quality_monitor_web_1 exited with code 1
```

Other info that might be useful?
```
$ ls /dev/ttyUSB*
/dev/ttyUSB0

$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

$ ls /dev/serial/by-path/
platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0
```

I can't tell if the problem is in the __init__ of aqm ... the queue.py "get" ... or something else. Any help would be appreciated. Thanks in advance.

(btw - the timezone is wrong. It looks like I'm posting this issue before the time on the log! I'm guessing that's a docker artifact?)

**Comment by easyas314** [comment]
As a follow-up, I found a raspberrypi.org blog post with some basic python serial code to pull data from the sensor. This is working. Here's my test code:
```
import serial, time
ser = serial.Serial('/dev/ttyUSB0')
while True:
	data = []
	for index in range(0,10):
		datum = ser.read()
		data.append(datum)
	pmtwofive = int.from_bytes(b''.join(data[2:4]), byteorder='little') / 10
	pmten = int.from_bytes(b''.join(data[4:6]), byteorder='little') / 10
	print(f"Data point: pm25 = {pmtwofive}  pm10 = {pmten}")
	time.sleep(10)
```
... so I guess that eliminates the /dev/ttyUSB0 question.

**Comment by tuftsanti** [comment]
Same issue here, hope the dev can give an explanation

**Comment by easyas314** [comment]
It looks like the problem really is the sds011.py line 234. It looks like an unhandled exception from the Queue package. Since the sds011 package is "archived" so I don't think it will be fixed. To fix the problem in this project, it'll require reworking it to either use another SDS011 package (looks to be several variations available) or live with a "specialized" package and use something like the Serial example above.

**Comment by tuftsanti** [comment]
Does your fork fix this?

**Comment by nordy1145** [comment]
I'm not sure of the actual issue, I got the same error.  I CTRL+C'd out of it.  Then just did a "make run" again and it all worked with no issues.

**Comment by tuftsanti** [comment]
> 
> 
> I'm not sure of the actual issue, I got the same error. I CTRL+C'd out of it. Then just did a "make run" again and it all worked with no issues.

Third make attempt it finally stuck the server, but now getting a blank page following

**Comment by syoung1999** [comment]
Looks like we're all running into the same issues, I also had to run the server a few times before it would run and not fail.  Happy to say that I'm getting data now.

**Comment by MujiSayed** [comment]
> import serial, time
> ser = serial.Serial('/dev/ttyUSB0')
> while True:
> 	data = []
> 	for index in range(0,10):
> 		datum = ser.read()
> 		data.append(datum)
> 	pmtwofive = int.from_bytes(b''.join(data[2:4]), byteorder='little') / 10
> 	pmten = int.from_bytes(b''.join(data[4:6]), byteorder='little') / 10
> 	print(f"Data point: pm25 = {pmtwofive}  pm10 = {pmten}")
> 	time.sleep(10)

looks like i got this to work and am getting data:
```sudo python3 sd.py
[sudo] password for basedmeezus:
Data point: pm25 = 5.7  pm10 = 6.2
Data point: pm25 = 5.6  pm10 = 6.1
Data point: pm25 = 5.7  pm10 = 6.2
Data point: pm25 = 4932.2  pm10 = 5.2```

to fix your issue, try running pip install serial
