### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by stevesmithnz** [rydercalmdown/pi_air_quality_monitor#11]
Hi,

Receiving the following when I try run it on Rasp 4

Traceback (most recent call last):
  File "/home/pi/airquality.py", line 14, in <module>
    aio.send('air-quality-pm-2-5', pmtwofive)
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_IO/client.py", line 167, in send_data
    return self.create_data(feed, payload)
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_IO/client.py", line 313, in create_data
    return Data.from_dict(self._post(path, data._asdict()))
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_IO/client.py", line 139, in _post
    self._handle_error(response)
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_IO/client.py", line 117, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs

**Comment by sharad643** [comment]
I have the same issue and havent been able to find a solution.
