### ISSUE TITLE
Make Build Step Fails

### ISSUE THREAD

**Issue by wildfirez98** [rydercalmdown/pi_air_quality_monitor#6]
Hello,

I have a Raspberry Pi 4 Compute Module 1gb ram LITE that I am attempting to install the air quality monitor on with an SDS011 sensor and am encountering the following error in the 'make build' step:

redis uses an image, skipping
Building web
Sending build context to Docker daemon  99.33kB
Step 1/7 : FROM python:3.8
 ---> 3f7cad4f2140
Step 2/7 : WORKDIR /code
 ---> Using cache
 ---> 8042ca9bef15
Step 3/7 : COPY src/requirements.txt .
 ---> Using cache
 ---> c43eaddc4c26
Step 4/7 : RUN pip install -r requirements.txt
 ---> Running in 9df8176db8df
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f88010 (most recent call first):
<no Python frame>
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'web' failed to build : Build failed
make: *** [Makefile:22: build] Error 1

Unfortunately I'm not entirely sure what the error is trying to tell me. Any suggestions?

**Comment by macminoz** [comment]
I have the same issue....I don't know how to fix it. Mine is stopping because:

`Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1.tar.gz (18 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tarfile.py", line 2292, in utime
    os.utime(targetpath, (tarinfo.mtime, tarinfo.mtime))
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)`

**Comment by mattsugihara** [comment]
@wildfirez98 [From this discussion](https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-735236388), it seems like there's an issue with `libseccomp2`, which Docker depends on. [The issue has been fixed](https://docs.linuxserver.io/faq), but it appears that the latest image of Raspberry Pi OS doesn't include that fix. You can install the updated version of `libseccomp2` on your your Pi by running:

```
$ wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
$ sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

Hopefully that helps!

Just a heads up, after after installing the updated version I was able to get this to build, but running `make run` failed with the following (potentially related) error.

```
ERROR: for pi_air_quality_monitor_web_1  __init__() got an unexpected keyword argument 'disable_buffering'

ERROR: for web  __init__() got an unexpected keyword argument 'disable_buffering'
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.7/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1182, in up
    attach_dependencies=attach_dependencies,
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 702, in up
    get_deps,
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 688, in do
    override_options=override_options,
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 586, in execute_convergence_plan
    containers, scale, timeout, detached, start
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 524, in _execute_convergence_start
    "Starting",
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 522, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 637, in start_container_if_stopped
    container.attach_log_stream()
  File "/usr/local/lib/python3.7/dist-packages/compose/container.py", line 202, in attach_log_stream
    self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
  File "/usr/local/lib/python3.7/dist-packages/compose/container.py", line 294, in attach
    return self.client.attach(self.id, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 58, in attach
    response = self._post(u, headers=headers, params=params, stream=True)
  File "/usr/local/lib/python3.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1348, in getresponse
    response = self.response_class(self.sock, method=self._method)
  File "/usr/local/lib/python3.7/dist-packages/docker/transport/unixconn.py", line 43, in response_class
    return httplib.HTTPResponse(sock, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'disable_buffering'
make[3]: *** [Makefile:6: run] Error 1
```

**Comment by macminoz** [comment]
great! I now can do make run but:

`Starting pi_air_quality_monitor_web_1   ... done
Attaching to pi_air_quality_monitor_redis_1, pi_air_quality_monitor_web_1
redis_1  | 1:C 01 Sep 2021 07:40:44.304 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 01 Sep 2021 07:40:44.305 # Redis version=6.2.5, bits=32, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 01 Sep 2021 07:40:44.305 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 01 Sep 2021 07:40:44.311 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 01 Sep 2021 07:40:44.317 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
redis_1  | 1:M 01 Sep 2021 07:40:44.319 * Running mode=standalone, port=6379.
redis_1  | 1:M 01 Sep 2021 07:40:44.320 # Server initialized
redis_1  | 1:M 01 Sep 2021 07:40:44.324 * Loading RDB produced by version 6.2.5
redis_1  | 1:M 01 Sep 2021 07:40:44.324 * RDB age 215 seconds
redis_1  | 1:M 01 Sep 2021 07:40:44.324 * RDB memory usage when created 0.63 Mb
redis_1  | 1:M 01 Sep 2021 07:40:44.324 * DB loaded from disk: 0.003 seconds
redis_1  | 1:M 01 Sep 2021 07:40:44.324 * Ready to accept connections
web_1    | Traceback (most recent call last):
web_1    |   File "app.py", line 15, in <module>
web_1    |     aqm = AirQualityMonitor()
web_1    |   File "/code/AirQualityMonitor.py", line 13, in __init__
web_1    |     self.sds = SDS011(port='/dev/ttyUSB0')
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 132, in __init__
web_1    |     self.probe()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 139, in probe
web_1    |     firmware_version_data = self.get_firmware_version()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 226, in get_firmware_version
web_1    |     return self.request(cmd)
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 234, in request
web_1    |     resp = self.rx_cmd_resp_queue.get(timeout=10)
web_1    |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
web_1    |     raise Empty
web_1    | _queue.Empty
pi_air_quality_monitor_web_1 exited with code 1`

**Comment by mattsugihara** [comment]
At a glance, that looks really similar to issue #1.

**Comment by wildfirez98** [comment]
> @wildfirez98 [From this discussion](https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-735236388), it seems like there's an issue with `libseccomp2`, which Docker depends on. [The issue has been fixed](https://docs.linuxserver.io/faq), but it appears that the latest image of Raspberry Pi OS doesn't include that fix. You can install the updated version of `libseccomp2` on your your Pi by running:
> 
> ```
> $ wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
> $ sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
> ```
> 
> Hopefully that helps!
> 
> Just a heads up, after after installing the updated version I was able to get this to build, but running `make run` failed with the following (potentially related) error.
> 
> ```
> ERROR: for pi_air_quality_monitor_web_1  __init__() got an unexpected keyword argument 'disable_buffering'
> 
> ERROR: for web  __init__() got an unexpected keyword argument 'disable_buffering'
> Traceback (most recent call last):
>   File "/usr/local/bin/docker-compose", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 81, in main
>     command_func()
>   File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 203, in perform_command
>     handler(command, command_options)
>   File "/usr/local/lib/python3.7/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
>     result = fn(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1186, in up
>     to_attach = up(False)
>   File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 1182, in up
>     attach_dependencies=attach_dependencies,
>   File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 702, in up
>     get_deps,
>   File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 108, in parallel_execute
>     raise error_to_reraise
>   File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 206, in producer
>     result = func(obj)
>   File "/usr/local/lib/python3.7/dist-packages/compose/project.py", line 688, in do
>     override_options=override_options,
>   File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 586, in execute_convergence_plan
>     containers, scale, timeout, detached, start
>   File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 524, in _execute_convergence_start
>     "Starting",
>   File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 108, in parallel_execute
>     raise error_to_reraise
>   File "/usr/local/lib/python3.7/dist-packages/compose/parallel.py", line 206, in producer
>     result = func(obj)
>   File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 522, in <lambda>
>     lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
>   File "/usr/local/lib/python3.7/dist-packages/compose/service.py", line 637, in start_container_if_stopped
>     container.attach_log_stream()
>   File "/usr/local/lib/python3.7/dist-packages/compose/container.py", line 202, in attach_log_stream
>     self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
>   File "/usr/local/lib/python3.7/dist-packages/compose/container.py", line 294, in attach
>     return self.client.attach(self.id, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/docker/utils/decorators.py", line 19, in wrapped
>     return f(self, resource_id, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/docker/api/container.py", line 58, in attach
>     response = self._post(u, headers=headers, params=params, stream=True)
>   File "/usr/local/lib/python3.7/dist-packages/docker/utils/decorators.py", line 46, in inner
>     return f(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 233, in _post
>     return self.post(url, **self._set_request_timeout(kwargs))
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.7/http/client.py", line 1348, in getresponse
>     response = self.response_class(self.sock, method=self._method)
>   File "/usr/local/lib/python3.7/dist-packages/docker/transport/unixconn.py", line 43, in response_class
>     return httplib.HTTPResponse(sock, *args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'disable_buffering'
> make[3]: *** [Makefile:6: run] Error 1
> ```

Thank you Matt that solved my issue in the build process and allowed me to run the program. However, it seems its not quite configured right or is still running into some type of issue. So everything loads and I can access the server on port 8000, but it has no data on the webpage? It merely displays the header 'Raspberry Pi Air Quality Monitor' in big bold text but thats it. The one thing that stands out in the output is the server address it lists http://172.18.0.3:8000/, but that is not the ip address of the device. Output file attached for review. Any thoughts?
[air_quality.txt](https://github.com/rydercalmdown/pi_air_quality_monitor/files/7101325/air_quality.txt)

**Comment by Billmcdowell61** [comment]
make run resulted in the following  no web access

make run
Starting pi_air_quality_monitor_redis_1 ... done
Starting pi_air_quality_monitor_web_1   ... done
Attaching to pi_air_quality_monitor_redis_1, pi_air_quality_monitor_web_1
redis_1  | 1:C 02 Oct 2021 19:56:53.283 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 02 Oct 2021 19:56:53.283 # Redis version=6.2.5, bits=32, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 02 Oct 2021 19:56:53.283 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 02 Oct 2021 19:56:53.288 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 02 Oct 2021 19:56:53.293 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
redis_1  | 1:M 02 Oct 2021 19:56:53.295 * Running mode=standalone, port=6379.
redis_1  | 1:M 02 Oct 2021 19:56:53.295 # Server initialized
redis_1  | 1:M 02 Oct 2021 19:56:53.297 * Loading RDB produced by version 6.2.5
redis_1  | 1:M 02 Oct 2021 19:56:53.298 * RDB age 89 seconds
redis_1  | 1:M 02 Oct 2021 19:56:53.298 * RDB memory usage when created 0.63 Mb
redis_1  | 1:M 02 Oct 2021 19:56:53.298 * DB loaded from disk: 0.001 seconds
redis_1  | 1:M 02 Oct 2021 19:56:53.298 * Ready to accept connections
web_1    | Traceback (most recent call last):
web_1    |   File "app.py", line 15, in <module>
web_1    |     aqm = AirQualityMonitor()
web_1    |   File "/code/AirQualityMonitor.py", line 13, in __init__
web_1    |     self.sds = SDS011(port='/dev/ttyUSB0')
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 132, in __init__
web_1    |     self.probe()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 139, in probe
web_1    |     firmware_version_data = self.get_firmware_version()
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 226, in get_firmware_version
web_1    |     return self.request(cmd)
web_1    |   File "/usr/local/lib/python3.8/site-packages/sds011/sds011.py", line 234, in request
web_1    |     resp = self.rx_cmd_resp_queue.get(timeout=10)
web_1    |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
web_1    |     raise Empty
web_1    | _queue.Empty
pi_air_quality_monitor_web_1 exited with code 1
